import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { buildBoardReport } from '../../lib/board-report';

/* ────────────────────────────────────────────────────────────
 * Shopify UK monthly channel report, for the board.
 *
 * Not a data dump and not an agency dashboard. The job is to say whether the
 * channel worked, at what true cost, and what happens next. Romano's four
 * principles, carried over from the Amazon deck unchanged:
 *
 *   1. Report the number nobody else reports. Platform dashboards show platform
 *      P&L only. Always build the full cost stack down to real contribution.
 *   2. Separate bought growth from earned growth.
 *   3. Never estimate. An unsourced figure reads PENDING, never a guess. One
 *      invented number and the board stops trusting all of them.
 *   4. Close on measurable tests, so next month opens against them.
 *
 * Rendered rather than generated: the Amazon deck is a PPTX regenerated by
 * hand, this reads live tables, so it can never be stale. Download is
 * window.print(), so the route carries no PDF dependency.
 *
 * British English. Nature-based therapeutics, never "supplements". No em dash.
 * ──────────────────────────────────────────────────────────── */

const money = v => {
  if (v == null || v === '') return '—';
  const n = Number(v);
  if (!Number.isFinite(n)) return '—';
  const abs = Math.abs(n).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  return `${n < 0 ? '−' : ''}£${abs}`;
};
const money0 = v => {
  const n = Number(v);
  if (!Number.isFinite(n) || v == null || v === '') return '—';
  return `${n < 0 ? '−' : ''}£${Math.abs(Math.round(n)).toLocaleString('en-GB')}`;
};
const int = v => (v == null || v === '' ? '—' : Number(v).toLocaleString('en-GB'));
const pct = v => (v == null || v === '' || !Number.isFinite(Number(v)) ? '—' : `${Number(v).toFixed(1)}%`);
const num = v => (v === '' || v == null ? null : Number(v));
const monthLabel = m => {
  if (!m) return '—';
  const [y, mo] = String(m).split('-');
  return new Date(Number(y), Number(mo) - 1, 1).toLocaleDateString('en-GB', { month: 'long', year: 'numeric' });
};
const shortMonth = m => {
  if (!m) return '—';
  const [y, mo] = String(m).split('-');
  return new Date(Number(y), Number(mo) - 1, 1).toLocaleDateString('en-GB', { month: 'short', year: '2-digit' });
};
function delta(a, b) {
  const x = num(a), y = num(b);
  if (x == null || y == null || x === 0) return null;
  return ((y - x) / Math.abs(x)) * 100;
}
const signed = d => (d == null ? '—' : `${d > 0 ? '+' : ''}${d.toFixed(1)}%`);

function Section({ n, kicker, title, children }) {
  return (
    <section className="br-sec">
      <div className="br-kick"><span>{n}</span>{kicker}</div>
      <h2 className="br-h2">{title}</h2>
      {children}
    </section>
  );
}

export default function BoardReport({ r }) {
  const router = useRouter();
  if (!r) return <div style={{ padding: 40 }}>No report data. Run the Shopify pulls first.</div>;

  const { cur, prev, ytd, mix, costStack, traffic, subs, owned, affiliates,
          products, reconciliation, amazon, months } = r;

  const trend = months.slice(-13);
  const maxNet = Math.max(...trend.map(m => num(m['Net Sales (£)']) || 0), 1);

  return (
    <>
      <Head><title>Natroceutics UK | Own Store Channel Report | {monthLabel(r.month)}</title></Head>

      <div className="bar">
        <Link href="/uk?s=shopify" className="back">← UK module</Link>
        <select
          className="bar-month"
          value={r.month}
          onChange={e => router.push(`/report/shopify-uk?month=${e.target.value}`)}
        >
          {[...months].reverse().map(m => (
            <option key={m.Month} value={m.Month}>{monthLabel(m.Month)}</option>
          ))}
        </select>
        <button onClick={() => window.print()} className="dl">Download report</button>
      </div>

      <div className="wrap">
        {/* ── cover ─────────────────────────────────── */}
        <div className="hero">
          <span className="eyebrow">Natroceutics® United Kingdom</span>
          <h1>Own Store · Channel Report</h1>
          <p className="sub">{monthLabel(r.month)} | uk.natroceutics.com</p>
          <div className="hero-meta">
            <div><span>Prepared by</span><b>Romano Leng · Channel Owner</b></div>
            <div><span>Currency</span><b>GBP</b></div>
            <div><span>Data period</span><b>{shortMonth(months[0]?.Month)} to {shortMonth(months[months.length - 1]?.Month)}</b></div>
            <div><span>Generated</span><b>{r.generatedAt}</b></div>
          </div>
        </div>

        {/* ── 01 executive summary ──────────────────── */}
        <Section n="01" kicker="EXECUTIVE SUMMARY" title="What the channel did, and what it cost">
          <div className="br-tiles">
            {[
              ['Net sales', money0(cur['Net Sales (£)']), signed(delta(prev['Net Sales (£)'], cur['Net Sales (£)'])), false],
              ['Orders', int(cur.Orders), signed(delta(prev.Orders, cur.Orders)), false],
              ['Contribution', money0(cur['Contribution (£)']), `${pct(cur['Contribution Margin %'])} margin`, false],
              ['Share of UK demand', pct(mix.shopifyShare), `Amazon ${money0(mix.amazon)}`, true],
            ].map(([label, value, note, dark]) => (
              <div key={label} className={`br-tile${dark ? ' br-tile--dark' : ''}`}>
                <span className="br-tile-l">{label}</span>
                <span className="br-tile-v">{value}</span>
                <span className="br-tile-n">{note}</span>
              </div>
            ))}
          </div>

          <ol className="br-points">
            <li>
              <b>The own store is small and profitable; Amazon is large and is not.</b>
              <p>
                The own store took {money0(cur['Net Sales (£)'])} and returned {money0(cur['Contribution (£)'])} before
                the costs still marked PENDING. Amazon took {money0(amazon.cur?.revenue)} in the same month and
                returned {money0(amazon.cur?.net)} after spending {money0(amazon.cur?.ads)} on advertising. One
                channel buys its growth; the other does not.
              </p>
            </li>
            <li>
              <b>Subscriptions are turning the store into an annuity.</b>
              <p>
                Recurring revenue reached {money0(subs.cur['Recurring Revenue (£)'])} this month
                ({pct(subs.cur['Recurring Share %'])} of subscription revenue), against a first-order
                figure of {money0(subs.cur['First Order Revenue (£)'])}. {subs.billing} subscribers billed
                inside the last cycle. That share has risen from under 5% a year ago.
              </p>
            </li>
            <li>
              <b>The contribution figure is not final and should not be read as profit.</b>
              <p>
                {costStack.pending.length} cost lines remain unsourced, and cost of goods currently covers
                {' '}{pct(cur['COGS Coverage %'])} of revenue. Both are named in section 04. Nothing here is
                estimated to fill those gaps.
              </p>
            </li>
          </ol>
        </Section>

        {/* ── 02 channel mix ────────────────────────── */}
        <Section n="02" kicker="CHANNEL MIX" title="Where UK demand goes, and who keeps the customer">
          <p className="br-lead">
            Amazon is the larger channel by revenue and the weaker one by economics. On the own store we
            keep the customer, the margin and the relationship. That is the strategic argument, and it is
            now measurable rather than asserted.
          </p>
          <div className="br-scroll">
            <table className="br-table">
              <thead>
                <tr><th>Measure</th><th className="r">Own store</th><th className="r">Amazon UK</th></tr>
              </thead>
              <tbody>
                <tr><td>Revenue</td><td className="r">{money(mix.shopify)}</td><td className="r">{money(mix.amazon)}</td></tr>
                <tr><td>Share of UK demand</td><td className="r">{pct(mix.shopifyShare)}</td><td className="r">{pct(mix.shopifyShare == null ? null : 100 - mix.shopifyShare)}</td></tr>
                <tr><td>Orders</td><td className="r">{int(cur.Orders)}</td><td className="r">{int(amazon.cur?.orders)}</td></tr>
                <tr><td>Advertising spent</td><td className="r">£0.00</td><td className="r">{money(amazon.cur?.ads)}</td></tr>
                <tr className="tot"><td>Result</td><td className="r">{money(cur['Contribution (£)'])}</td><td className="r">{money(amazon.cur?.net)}</td></tr>
                <tr><td>Basis of that result</td><td className="r sm">Before PENDING costs</td><td className="r sm">Sellerboard net profit</td></tr>
              </tbody>
            </table>
          </div>
          <div className="br-note br-note--key">
            <b>Read the two results carefully.</b> They are not like for like: the own-store figure excludes
            the cost lines in section 04, and the Amazon figure is after all platform costs but before the
            agency retainer. The point is not the exact gap, it is that the smaller channel produced more
            contribution while spending nothing on advertising.
          </div>
        </Section>

        {/* ── 03 profit and loss ────────────────────── */}
        <Section n="03" kicker="PROFIT AND LOSS" title={`${monthLabel(r.month)} against ${monthLabel(prev.Month)}`}>
          <div className="br-scroll">
            <table className="br-table">
              <thead>
                <tr>
                  <th>Line</th><th className="r">{shortMonth(r.month)}</th>
                  <th className="r">{shortMonth(prev.Month)}</th><th className="r">Change</th><th className="r">Basis</th>
                </tr>
              </thead>
              <tbody>
                {[
                  ['Gross sales', 'Gross Sales (£)', false, 'Actual'],
                  ['Discounts', 'Discounts (£)', false, 'Actual'],
                  ['Returns', 'Returns (£)', false, 'Actual'],
                  ['Net sales', 'Net Sales (£)', true, 'Actual'],
                  ['Cost of goods', 'COGS (£)', false, `${pct(cur['COGS Coverage %'])} coverage`],
                  ['Payment processing', 'Payment Fees (£)', false, 'Actual, per transaction'],
                  ['Contribution', 'Contribution (£)', true, 'Before section 04'],
                ].map(([label, key, tot, basis]) => {
                  const neg = key === 'COGS (£)' || key === 'Payment Fees (£)';
                  const a = num(cur[key]), b = num(prev[key]);
                  const fmt = v => (v == null ? '—' : money(neg && v > 0 ? -v : v));
                  return (
                    <tr key={key} className={tot ? 'tot' : ''}>
                      <td>{label}</td>
                      <td className={`r${neg ? ' neg' : ''}`}>{fmt(a)}</td>
                      <td className={`r${neg ? ' neg' : ''}`}>{fmt(b)}</td>
                      <td className="r">{signed(delta(b, a))}</td>
                      <td className="r sm">{basis}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          <div className="br-trend">
            <div className="br-trend-title">Net sales, {trend.length} months</div>
            <div className="br-bars">
              {trend.map(m => {
                const v = num(m['Net Sales (£)']) || 0;
                return (
                  <div key={m.Month} className={`br-bar${m.Month === r.month ? ' on' : ''}`}>
                    <div className="br-bar-fill" style={{ height: `${Math.max(3, (v / maxNet) * 100)}%` }} />
                    <span className="br-bar-l">{shortMonth(m.Month).split(' ')[0]}</span>
                  </div>
                );
              })}
            </div>
            <p className="br-cap">
              Growth has been steady rather than spiky, which matters: a channel that grows without
              advertising is compounding, not buying.
            </p>
          </div>
        </Section>

        {/* ── 04 true channel cost ──────────────────── */}
        <Section n="04" kicker="TRUE CHANNEL COST" title="The full cost stack, including what is missing">
          <p className="br-lead">
            Shopify reports revenue. It does not know what the goods cost to ship, what the platform costs
            to run, or what anyone is paid to run it. This is the number no dashboard supplies.
          </p>
          <div className="br-scroll">
            <table className="br-table">
              <thead><tr><th>Cost layer</th><th>Source</th><th className="r">{shortMonth(r.month)}</th></tr></thead>
              <tbody>
                <tr className="tot">
                  <td>Contribution after goods and payment fees</td>
                  <td className="sm">Shopify, measured</td>
                  <td className="r">{money(costStack.contribution)}</td>
                </tr>
                {costStack.sourced.map(c => (
                  <tr key={c.Key}>
                    <td>{c.Label}</td>
                    <td className="sm">{c.Source}</td>
                    <td className="r neg">{c.Value === '' ? c.Status : money(-Math.abs(num(c.Value)))}</td>
                  </tr>
                ))}
                <tr className="tot">
                  <td>After sourced costs</td>
                  <td className="sm">Everything we can measure</td>
                  <td className="r">{money(costStack.afterSourced)}</td>
                </tr>
                {costStack.pending.map(c => (
                  <tr key={c.Key}>
                    <td>{c.Label}</td>
                    <td className="sm">{c.Source}</td>
                    <td className="r"><span className="pend">PENDING</span></td>
                  </tr>
                ))}
                <tr className="tot">
                  <td>True channel contribution</td>
                  <td className="sm">Not calculable until the lines above are sourced</td>
                  <td className="r"><span className="pend">PENDING</span></td>
                </tr>
              </tbody>
            </table>
          </div>
          {costStack.queries.map(q => (
            <div key={q.Key} className="br-note br-note--warn">
              <b>{q.Label}: unresolved.</b>
              <p>{q.Note}</p>
            </div>
          ))}
          <div className="br-note">
            <b>Why this is stated rather than filled in.</b>
            <p>
              A missing cost shown as zero silently overstates profit, and one invented number costs the
              board its trust in all of them. {costStack.pending.length} lines read PENDING because nobody
              has supplied them yet, not because they are nil.
            </p>
          </div>
        </Section>

        {/* ── 05 acquisition ────────────────────────── */}
        <Section n="05" kicker="ACQUISITION" title="All of this growth was earned">
          <div className="br-scroll">
            <table className="br-table">
              <thead><tr><th>Source</th><th className="r">{shortMonth(r.month)}</th><th className="r">{shortMonth(traffic.prev.Month)}</th></tr></thead>
              <tbody>
                {[['Sessions', 'Sessions'], ['Direct', 'Sessions: direct'], ['Search', 'Sessions: search'],
                  ['Email', 'Sessions: email'], ['Social', 'Sessions: social']].map(([l, k]) => (
                  <tr key={k} className={k === 'Sessions' ? 'tot' : ''}>
                    <td>{l}</td>
                    <td className="r">{int(traffic.cur[k])}</td>
                    <td className="r">{int(traffic.prev[k])}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="br-note br-note--key">
            <b>There is no paid acquisition on this channel.</b>
            <p>
              {int(traffic.cur['Sessions: social'])} sessions came from social and {int(traffic.cur['Sessions: email'])} from
              email. Everything else was direct or search. Amazon spent {money0(amazon.cur?.ads)} in the same
              month to grow its revenue. The own store grew without buying a single visit, which is the
              difference between a business compounding and a business renting demand.
            </p>
          </div>
          <p className="br-cap">
            Session attribution understates: only {int(traffic.cur['Completed Checkout'])} of {int(cur.Orders)} orders
            tie to a tracked session, so the reported conversion rate is a floor. Treat the funnel as
            directional and the order count as fact.
          </p>
        </Section>

        {/* ── 06 owned channel ──────────────────────── */}
        <Section n="06" kicker="OWNED CHANNEL" title="Email is working automatically and idle deliberately">
          <div className="br-tiles br-tiles--3">
            <div className="br-tile"><span className="br-tile-l">Flow revenue, 12 months</span>
              <span className="br-tile-v">{money0(owned.flowRevenue)}</span>
              <span className="br-tile-n">{owned.liveFlows} flows live</span></div>
            <div className="br-tile"><span className="br-tile-l">Broadcast revenue, 12 months</span>
              <span className="br-tile-v">{money0(owned.campaignRevenue)}</span>
              <span className="br-tile-n">{owned.sentCampaigns} campaigns ever sent</span></div>
            <div className="br-tile br-tile--dark"><span className="br-tile-l">Last campaign</span>
              <span className="br-tile-v">{owned.lastCampaign || '—'}</span>
              <span className="br-tile-n">The gap, in one date</span></div>
          </div>
          <div className="br-scroll">
            <table className="br-table">
              <thead><tr><th>Flow</th><th className="r">Recipients</th><th className="r">Open rate</th><th className="r">Revenue</th></tr></thead>
              <tbody>
                {owned.flows.filter(f => num(f['Revenue (£)']) > 0).slice(0, 8).map(f => (
                  <tr key={f.Flow}>
                    <td>{f.Flow}</td>
                    <td className="r">{int(f.Recipients)}</td>
                    <td className="r">{pct(f['Open Rate %'])}</td>
                    <td className="r">{money(f['Revenue (£)'])}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="br-note br-note--warn">
            <b>Two things to fix before spending on email.</b>
            <p>
              Klaviyo has recorded no orders since June, which means the Shopify integration has stopped
              feeding it and every purchase-triggered flow is silently dead: post-purchase, winback, review
              request. And {owned.sentCampaigns} campaigns in a year against {owned.liveFlows} live flows
              says the automated side has been carrying the channel alone.
            </p>
          </div>
        </Section>

        {/* ── 07 subscriptions ──────────────────────── */}
        <Section n="07" kicker="SUBSCRIPTIONS" title="The annuity, counted separately from acquisition">
          <div className="br-scroll">
            <table className="br-table">
              <thead>
                <tr><th>Month</th><th className="r">New</th><th className="r">First-order revenue</th>
                  <th className="r">Recurring orders</th><th className="r">Recurring revenue</th><th className="r">Recurring share</th></tr>
              </thead>
              <tbody>
                {subs.monthly.slice(-6).map(m => (
                  <tr key={m.Month} className={m.Month === r.month ? 'tot' : ''}>
                    <td>{shortMonth(m.Month)}</td>
                    <td className="r">{int(m['New Subscribers'])}</td>
                    <td className="r">{money(m['First Order Revenue (£)'])}</td>
                    <td className="r">{int(m['Recurring Orders'])}</td>
                    <td className="r">{money(m['Recurring Revenue (£)'])}</td>
                    <td className="r">{pct(m['Recurring Share %'])}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="br-note br-note--key">
            <b>Recurring revenue is {money0(subs.recurringTotal)} since inception and the share is rising.</b>
            <p>
              First-order revenue is acquisition and happens once. Recurring revenue arrives without
              spending anything to win it again, which is why the two are never added together here.
              {subs.declined > 0 && ` ${subs.declined} subscribers currently have a declined card: that is the cheapest revenue on the channel, because the customer is already won.`}
            </p>
          </div>
        </Section>

        {/* ── 08 product ────────────────────────────── */}
        <Section n="08" kicker="PRODUCT" title="Where the revenue and the margin actually sit">
          <div className="br-scroll">
            <table className="br-table">
              <thead>
                <tr><th>Product</th><th className="r">Units</th><th className="r">Net sales</th>
                  <th className="r">Cost of goods</th><th className="r">Gross profit</th><th className="r">Margin</th></tr>
              </thead>
              <tbody>
                {products.all.slice(0, 12).map(p => {
                  const missing = p['COGS (£)'] === '' || p['COGS (£)'] == null;
                  return (
                    <tr key={p.Product}>
                      <td>{p.Product}</td>
                      <td className="r">{int(p.Units)}</td>
                      <td className="r">{money(p['Net Sales (£)'])}</td>
                      <td className={`r${missing ? '' : ' neg'}`}>
                        {missing ? <span className="pend">NO COST</span> : money(-Math.abs(num(p['COGS (£)'])))}
                      </td>
                      <td className="r">{missing ? '—' : money(p['Gross Profit (£)'])}</td>
                      <td className="r">{missing ? '—' : pct(p['Margin %'])}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
          {products.noCost.length > 0 && (
            <div className="br-note br-note--warn">
              <b>{products.noCost.length} of {products.all.length} products sold this month have no unit cost.</b>
              <p>
                They account for {money0(products.noCost.reduce((s, p) => s + (num(p['Net Sales (£)']) || 0), 0))} of
                revenue, which is why cost of goods covers only {pct(cur['COGS Coverage %'])}. Setting cost per
                item in Shopify is the single cheapest way to complete this report.
              </p>
            </div>
          )}
        </Section>

        {/* ── 09 margin recovery ────────────────────── */}
        <Section n="09" kicker="MARGIN RECOVERY" title="Where price or cost needs a second look">
          {products.thin.length === 0 ? (
            <p className="br-lead">
              No costed product is running below a 60% gross margin this month. That is a healthy position
              and worth stating plainly rather than leaving the section empty.
            </p>
          ) : (
            <>
              <div className="br-scroll">
                <table className="br-table">
                  <thead><tr><th>Product</th><th className="r">Units</th><th className="r">Net sales</th><th className="r">Margin</th><th className="r">Unit cost</th></tr></thead>
                  <tbody>
                    {products.thin.slice(0, 8).map(p => (
                      <tr key={p.Product}>
                        <td>{p.Product}</td>
                        <td className="r">{int(p.Units)}</td>
                        <td className="r">{money(p['Net Sales (£)'])}</td>
                        <td className="r neg">{pct(p['Margin %'])}</td>
                        <td className="r">{money(p['Unit Cost (£)'])}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="br-cap">
                Margin here is before shipping and platform costs, so the true figure is lower. These are
                the SKUs where a price review or a supplier conversation earns the most.
              </p>
            </>
          )}
          <div className="br-note">
            <b>Affiliate commission is the most expensive acquisition the business buys.</b>
            <p>
              {affiliates.earning} of {affiliates.total} affiliates have ever referred an order, at a blended
              {' '}{pct(affiliates.rate)} commission. That rate sits above the margin of several products in
              section 08, so affiliate-driven sales of those SKUs may be unprofitable. Worth checking before
              recruiting more.
            </p>
          </div>
        </Section>

        {/* ── 10 reconciliation ─────────────────────── */}
        <Section n="10" kicker="RECONCILIATION" title="Evidence that these numbers are right">
          <p className="br-lead">
            Shopify Payments deposits real money into the bank. The P&amp;L says what the orders were worth.
            If those disagree, something is wrong, and nothing else in this report can tell you.
          </p>
          <div className="br-scroll">
            <table className="br-table">
              <thead>
                <tr><th>Month</th><th className="r">Paid out</th><th className="r">Shopify fees</th>
                  <th className="r">Fees per P&amp;L</th><th className="r">Variance</th></tr>
              </thead>
              <tbody>
                {[...reconciliation.all].sort((a, b) => String(b.Month).localeCompare(String(a.Month))).slice(0, 6).map(p => (
                  <tr key={p.Month} className={p.Month === r.month ? 'tot' : ''}>
                    <td>{shortMonth(p.Month)}</td>
                    <td className="r">{money(p['Paid Out (£)'])}</td>
                    <td className="r">{money(p['Shopify Fees (£)'])}</td>
                    <td className="r">{p['Fees per P&L (£)'] === '' ? '—' : money(p['Fees per P&L (£)'])}</td>
                    <td className="r">{p['Fee Variance (£)'] === '' ? '—' : money(p['Fee Variance (£)'])}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="br-note br-note--key">
            <b>The largest monthly variance is {money(reconciliation.worstVariance)}.</b>
            <p>
              Payouts are grouped by the date Shopify issued them and orders pay out days later, so a month
              of payouts never equals a month of sales. The fee comparison is the meaningful one, and a
              variance this small is the strongest evidence that the figures throughout this report are
              sound. A variance that starts growing is the earliest warning that they are not.
            </p>
          </div>
        </Section>

        {/* ── 11 year to date ───────────────────────── */}
        {ytd && (
          <Section n="11" kicker="YEAR TO DATE" title={`${ytd.Period}`}>
            <div className="br-tiles">
              <div className="br-tile"><span className="br-tile-l">Net sales</span>
                <span className="br-tile-v">{money0(ytd['Net Sales (£)'])}</span>
                <span className="br-tile-n">{int(ytd.Orders)} orders over {ytd.Months} months</span></div>
              <div className="br-tile"><span className="br-tile-l">Cost of goods</span>
                <span className="br-tile-v">{money0(ytd['COGS (£)'])}</span>
                <span className="br-tile-n">{pct(ytd['COGS Coverage %'])} coverage</span></div>
              <div className="br-tile"><span className="br-tile-l">Payment fees</span>
                <span className="br-tile-v">{money0(ytd['Payment Fees (£)'])}</span>
                <span className="br-tile-n">Actual, per transaction</span></div>
              <div className="br-tile br-tile--dark"><span className="br-tile-l">Contribution</span>
                <span className="br-tile-v">{money0(ytd['Contribution (£)'])}</span>
                <span className="br-tile-n">{pct(ytd['Contribution Margin %'])} before PENDING</span></div>
            </div>
            <p className="br-cap">
              Cost-of-goods coverage is weighted by revenue rather than averaged across months: a small
              month and a large one must not count equally.
            </p>
          </Section>
        )}

        {/* ── 12 actions ────────────────────────────── */}
        <Section n="12" kicker="ACTIONS" title="What happens next, and how it will be measured">
          <div className="br-scroll">
            <table className="br-table">
              <thead><tr><th>Action</th><th>Owner</th><th>By when</th></tr></thead>
              <tbody>
                <tr><td><b>Confirm VAT treatment on own-store sales</b></td><td>Grant</td><td className="sm">Before August close</td></tr>
                <tr><td><b>Repair the Klaviyo to Shopify integration</b>, then audit which flows resumed firing</td><td>Romano</td><td className="sm">This week</td></tr>
                <tr><td>Set unit costs for the {products.noCost.length} products missing them</td><td>Romano</td><td className="sm">This week</td></tr>
                <tr><td>Obtain pick, pack and shipping cost per order</td><td>Romano / Jason</td><td className="sm">Before next report</td></tr>
                <tr><td>Confirm Shopify plan fee and app subscription total</td><td>Romano</td><td className="sm">Before next report</td></tr>
                <tr><td>Recover the {subs.declined} subscribers with a declined card</td><td>Romano</td><td className="sm">This week</td></tr>
                <tr><td>Send the first broadcast campaign since {owned.lastCampaign}</td><td>Romano</td><td className="sm">August</td></tr>
                <tr><td>Confirm whether any agency retainer covers the own store</td><td>Morgan / Kunle</td><td className="sm">This month</td></tr>
              </tbody>
            </table>
          </div>
          <div className="br-note br-note--key">
            <b>Measured next month</b>
            <p>
              Cost-of-goods coverage at 100% · every PENDING line in section 04 either sourced or explained ·
              Klaviyo recording orders again · at least one campaign sent · recurring share holding above
              {' '}{pct(subs.cur['Recurring Share %'])} · fee variance still inside {money(reconciliation.worstVariance)}.
            </p>
          </div>
        </Section>

        {/* ── sources ───────────────────────────────── */}
        <Section n="13" kicker="SOURCES" title="Basis of preparation">
          <div className="br-sources">
            {[
              ['SHOPIFY ADMIN API', 'Orders, transactions and per-variant unit costs for uk.natroceutics.com, read live. Cancelled and test orders are excluded. Payment fees are the sum of actual per-transaction fees on successful charges; declined attempts carry a fee record in the API and are not counted.'],
              ['SHOPIFY PAYMENTS', 'Payouts by issue date, with the fee reconciliation in section 10.'],
              ['SHOPIFY ANALYTICS', 'Sessions, referrer split and returning-customer rate. Session attribution is incomplete by nature and is treated as directional.'],
              ['RECHARGE, VIA SHOPIFY', 'Subscription state is read from order and customer tags rather than the Recharge API. First-order and recurring revenue are separated by order tag.'],
              ['KLAVIYO', 'Flow and campaign value reports, which attribute revenue to the message that drove the sale. The Placed Order metric is NOT used for attribution: it counts every order in the store.'],
              ['GOAFFPRO', 'Referred orders and commission, read live. This replaced a hand-maintained record that had stopped being updated in June and understated commission.'],
              ['AMAZON', 'Sellerboard profit and loss held in the OS, used for the channel comparison in section 02.'],
              ['EXCLUSIONS', `Shipping cost, platform fee, app subscriptions and any agency share are not included in contribution because they are not yet sourced. They are listed individually in section 04 rather than netted to zero.`],
              ['CURRENCY AND VAT', 'All figures GBP. Own-store sales are stated before VAT pending the confirmation in section 04; Amazon figures are after VAT. The two are not directly comparable until that is resolved.'],
            ].map(([k, v]) => (
              <div key={k} className="br-source"><span>{k}</span><p>{v}</p></div>
            ))}
          </div>
        </Section>

        <footer className="br-foot">
          Generated by Natroceutics OS from live data on {r.generatedAt}. Every figure is measured or marked
          PENDING. No figure is estimated.
          <div className="br-sig">NATROCEUTICS® UK · {monthLabel(r.month).toUpperCase()} · CONFIDENTIAL</div>
        </footer>
      </div>

      <style jsx global>{`
        :root{--f:#1d4130;--f7:#2a5c45;--f6:#406550;--ch:#2d2a26;--ch7:#5b554d;
              --cr:#f4f6f5;--hair:#dfe4e8;--navy:#414f6d;--navy-fg:#2c3a56;--navy-bg:#eef1f6;}
        *{box-sizing:border-box;margin:0;padding:0}
        body{background:#fff;color:var(--ch);font-family:'Manrope',system-ui,-apple-system,sans-serif;
             line-height:1.6;padding:0 0 64px;-webkit-font-smoothing:antialiased}
        .wrap{max-width:900px;margin:0 auto;padding:0 24px}

        .bar{position:sticky;top:0;z-index:20;display:flex;align-items:center;gap:12px;
             padding:12px 24px;background:rgba(255,255,255,.95);backdrop-filter:blur(8px);
             border-bottom:1px solid var(--hair)}
        .back{font-size:13px;color:var(--f6);text-decoration:none;font-weight:500}
        .bar-month{margin-left:auto;font-family:inherit;font-size:13px;padding:8px 11px;
                   border:1px solid var(--hair);border-radius:8px;background:#fff;color:var(--ch)}
        .dl{background:var(--f);color:#eef2ef;border:0;border-radius:8px;padding:10px 18px;
            font-family:inherit;font-size:13px;font-weight:600;letter-spacing:.04em;cursor:pointer}

        .hero{background:var(--f);color:#eef2ef;padding:40px 34px;margin:28px 0 20px;border-radius:12px}
        .eyebrow{font-size:10px;font-weight:600;letter-spacing:.16em;text-transform:uppercase;color:#9dbcaa}
        .hero h1{font-size:27px;font-weight:700;letter-spacing:.09em;text-transform:uppercase;margin:12px 0 6px;line-height:1.25}
        .hero .sub{font-weight:300;font-size:14px;color:#c9d8cf}
        .hero-meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:14px;
                   margin-top:26px;padding-top:20px;border-top:1px solid #2a5340}
        .hero-meta span{display:block;font-family:'DM Mono',ui-monospace,monospace;font-size:8.5px;
                        letter-spacing:.13em;text-transform:uppercase;color:#7f9c8a;margin-bottom:3px}
        .hero-meta b{font-size:12.5px;font-weight:500;color:#dfe8e2}

        .br-sec{margin-bottom:40px}
        .br-kick{display:flex;align-items:center;gap:10px;font-family:'DM Mono',ui-monospace,monospace;
                 font-size:9.5px;font-weight:600;letter-spacing:.15em;color:var(--f6);text-transform:uppercase}
        .br-kick span{color:var(--navy)}
        .br-h2{font-size:20px;font-weight:700;letter-spacing:.02em;color:var(--f);margin:8px 0 14px;line-height:1.3}
        .br-lead{font-size:14px;font-weight:300;line-height:1.65;color:var(--ch7);margin-bottom:16px;max-width:66ch}

        .br-tiles{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px;margin-bottom:18px}
        .br-tiles--3{grid-template-columns:repeat(auto-fit,minmax(180px,1fr))}
        .br-tile{background:var(--cr);border:1px solid var(--hair);border-radius:10px;padding:16px 18px}
        .br-tile--dark{background:var(--f);border-color:var(--f)}
        .br-tile-l{display:block;font-family:'DM Mono',ui-monospace,monospace;font-size:8.5px;font-weight:600;
                   letter-spacing:.13em;text-transform:uppercase;color:var(--f6);margin-bottom:8px}
        .br-tile--dark .br-tile-l{color:#9dbcaa}
        .br-tile-v{display:block;font-family:'DM Mono',ui-monospace,monospace;font-size:23px;
                   color:var(--navy-fg);line-height:1.1}
        .br-tile--dark .br-tile-v{color:#eef2ef}
        .br-tile-n{display:block;font-size:11.5px;font-weight:300;color:var(--ch7);margin-top:7px}
        .br-tile--dark .br-tile-n{color:#c9d8cf}

        .br-points{list-style:none;counter-reset:p;margin-top:6px}
        .br-points li{counter-increment:p;padding-left:34px;position:relative;margin-bottom:16px}
        .br-points li::before{content:counter(p,decimal-leading-zero);position:absolute;left:0;top:1px;
          font-family:'DM Mono',ui-monospace,monospace;font-size:11px;color:var(--navy)}
        .br-points b{display:block;font-size:14px;font-weight:700;color:var(--f);margin-bottom:4px}
        .br-points p{font-size:13px;font-weight:300;line-height:1.6;color:var(--ch7);max-width:70ch}

        .br-scroll{overflow-x:auto;-webkit-overflow-scrolling:touch}
        .br-table{width:100%;min-width:520px;border-collapse:collapse;background:#fff;
                  border:1px solid var(--hair);border-radius:8px}
        .br-table th{font-family:'DM Mono',ui-monospace,monospace;font-size:8.5px;font-weight:600;
          letter-spacing:.1em;text-transform:uppercase;color:var(--f6);text-align:left;
          padding:10px 12px;background:var(--cr);border-bottom:1px solid var(--hair);white-space:nowrap}
        .br-table td{padding:9px 12px;border-bottom:1px solid var(--hair);font-size:13px}
        .br-table tr:last-child td{border-bottom:none}
        .br-table .r{text-align:right;font-family:'DM Mono',ui-monospace,monospace;font-size:12.5px;
                     white-space:nowrap;color:var(--navy-fg)}
        .br-table th.r{text-align:right;font-family:'DM Mono',ui-monospace,monospace;color:var(--f6)}
        .br-table .sm{font-size:11px;font-weight:300;color:#8a939c;font-family:inherit}
        .br-table .neg{color:#8c4a3a}
        .br-table tr.tot td{background:var(--cr);font-weight:700;color:var(--f)}
        .pend{font-family:'DM Mono',ui-monospace,monospace;font-size:9.5px;font-weight:600;
              letter-spacing:.06em;color:var(--f6)}

        .br-note{margin-top:14px;padding:15px 17px;background:var(--cr);border:1px solid var(--hair);
                 border-left:3px solid var(--f6);border-radius:8px}
        .br-note--key{border-left-color:var(--navy)}
        .br-note--warn{border-left-color:#8c4a3a}
        .br-note b{display:block;font-size:12.5px;font-weight:700;color:var(--f);margin-bottom:5px}
        .br-note p{font-size:13px;font-weight:300;line-height:1.62;color:var(--ch7);max-width:72ch}
        .br-cap{margin-top:10px;font-size:11.5px;font-weight:300;line-height:1.55;color:#8a939c;max-width:72ch}

        .br-trend{margin-top:20px}
        .br-trend-title{font-family:'DM Mono',ui-monospace,monospace;font-size:8.5px;font-weight:600;
          letter-spacing:.13em;text-transform:uppercase;color:var(--f6);margin-bottom:10px}
        .br-bars{display:flex;align-items:flex-end;gap:5px;height:110px;
                 padding:0 2px 0;border-bottom:1px solid var(--hair)}
        .br-bar{flex:1;display:flex;flex-direction:column;justify-content:flex-end;height:100%;position:relative}
        .br-bar-fill{background:var(--navy-bg);border-radius:3px 3px 0 0;border:1px solid #d6dde9;border-bottom:0}
        .br-bar.on .br-bar-fill{background:var(--f);border-color:var(--f)}
        .br-bar-l{font-family:'DM Mono',ui-monospace,monospace;font-size:8px;color:#8a939c;
                  text-align:center;margin-top:5px;position:absolute;bottom:-16px;left:0;right:0}

        .br-sources{display:flex;flex-direction:column;gap:12px}
        .br-source{display:grid;grid-template-columns:170px 1fr;gap:16px;padding-bottom:12px;
                   border-bottom:1px solid var(--hair)}
        .br-source:last-child{border-bottom:0}
        .br-source span{font-family:'DM Mono',ui-monospace,monospace;font-size:8.5px;font-weight:600;
          letter-spacing:.11em;color:var(--f6)}
        .br-source p{font-size:12px;font-weight:300;line-height:1.6;color:var(--ch7)}

        .br-foot{margin-top:26px;padding-top:18px;border-top:1px solid var(--hair);
                 font-size:11px;color:#8a939c;font-weight:300}
        .br-sig{font-family:'DM Mono',ui-monospace,monospace;font-size:10px;letter-spacing:.05em;
                margin-top:6px;color:#a7aeb6}

        @media (max-width:640px){
          .wrap{padding:0 14px}
          .hero{padding:28px 22px}
          .hero h1{font-size:20px}
          .br-h2{font-size:17px}
          .br-source{grid-template-columns:1fr;gap:4px}
          .br-bars{height:80px}
        }
        @media print{
          .bar{display:none}
          .hero,.br-tile--dark{-webkit-print-color-adjust:exact;print-color-adjust:exact}
          .br-sec{break-inside:avoid}
          body{padding-bottom:0}
          .wrap{max-width:none}
        }
      `}</style>
    </>
  );
}

export async function getServerSideProps({ query }) {
  try {
    const r = await buildBoardReport(query.month || null);
    return { props: { r: JSON.parse(JSON.stringify(r)) } };
  } catch (e) {
    console.error('[board-report]', e.message);
    return { props: { r: null } };
  }
}
